# Generated by Django 6.0.5 on 2026-05-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analise_exploratoria', '0006_experimento_execucaoanalise_experimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoAnonimizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_documentos_anonimizados', models.IntegerField()),
                ('total_spans_substituidos', models.IntegerField()),
                ('distribuicao_marcadores_json', models.JSONField(blank=True, null=True)),
                ('coverage', models.FloatField(blank=True, null=True)),
                ('precision_anon', models.FloatField(blank=True, null=True)),
                ('levenshtein_ratio', models.FloatField(blank=True, null=True)),
                ('f1_downstream_original', models.FloatField(blank=True, null=True)),
                ('f1_downstream_anonimizado', models.FloatField(blank=True, null=True)),
                ('delta_f1', models.FloatField(blank=True, null=True)),
                ('delta_f1_por_entidade_json', models.JSONField(blank=True, null=True)),
                ('caminho_corpus_anonimizado', models.CharField(blank=True, max_length=500, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('experimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonimizacoes', to='analise_exploratoria.experimento')),
            ],
            options={
                'verbose_name': 'Execução de Anonimização',
                'verbose_name_plural': 'Execuções de Anonimização',
                'db_table': 'tb_anonclin_execucao_anonimizacao',
                'ordering': ['-criado_em'],
            },
        ),
    ]
