# Generated by Django 6.0.5 on 2026-05-21 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analise_exploratoria', '0006_experimento_execucaoanalise_experimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoAnotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('experimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_anotacao', to='analise_exploratoria.experimento')),
            ],
            options={
                'verbose_name': 'Sessão de Anotação',
                'db_table': 'tb_anonclin_anotador_sessao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Sentenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField()),
                ('doc_type', models.CharField(max_length=20)),
                ('ordem', models.IntegerField()),
                ('tokens', models.JSONField()),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentencas', to='anotador.sessaoanotacao')),
            ],
            options={
                'verbose_name': 'Sentença',
                'db_table': 'tb_anonclin_anotador_sentenca',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='AnotacaoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField()),
                ('label', models.CharField(choices=[('O', 'O — Fora de entidade'), ('B-PESSOA', 'B-PESSOA'), ('I-PESSOA', 'I-PESSOA'), ('B-DATA', 'B-DATA'), ('I-DATA', 'I-DATA'), ('B-ENDERECO', 'B-ENDERECO'), ('I-ENDERECO', 'I-ENDERECO'), ('B-CONTATO', 'B-CONTATO'), ('I-CONTATO', 'I-CONTATO'), ('B-DOCUMENTO', 'B-DOCUMENTO'), ('I-DOCUMENTO', 'I-DOCUMENTO'), ('B-HORA', 'B-HORA'), ('I-HORA', 'I-HORA'), ('B-INSTITUICAO', 'B-INSTITUICAO'), ('I-INSTITUICAO', 'I-INSTITUICAO')], default='O', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anotador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to=settings.AUTH_USER_MODEL)),
                ('sentenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='anotador.sentenca')),
            ],
            options={
                'verbose_name': 'Anotação de Token',
                'db_table': 'tb_anonclin_anotador_token',
                'ordering': ['sentenca', 'posicao'],
                'unique_together': {('sentenca', 'anotador', 'posicao')},
            },
        ),
        migrations.CreateModel(
            name='AdjudicacaoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField()),
                ('label', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sentenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudicacoes', to='anotador.sentenca')),
            ],
            options={
                'verbose_name': 'Adjudicação de Token',
                'db_table': 'tb_anonclin_anotador_adjudicacao',
                'ordering': ['sentenca', 'posicao'],
                'unique_together': {('sentenca', 'posicao')},
            },
        ),
    ]
