# Generated by Django 6.0.5 on 2026-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField()),
                ('total_prescricoes', models.IntegerField()),
                ('total_pareceres', models.IntegerField()),
                ('pacientes_unicos', models.IntegerField()),
                ('periodo_inicio', models.DateField(null=True)),
                ('periodo_fim', models.DateField(null=True)),
                ('total_hospitais', models.IntegerField()),
                ('tokens_presc_min', models.IntegerField()),
                ('tokens_presc_media', models.FloatField()),
                ('tokens_presc_mediana', models.IntegerField()),
                ('tokens_presc_max', models.IntegerField()),
                ('tokens_presc_p25', models.IntegerField()),
                ('tokens_presc_p75', models.IntegerField()),
                ('tokens_par_min', models.IntegerField()),
                ('tokens_par_media', models.FloatField()),
                ('tokens_par_mediana', models.IntegerField()),
                ('tokens_par_max', models.IntegerField()),
                ('tokens_par_p25', models.IntegerField()),
                ('tokens_par_p75', models.IntegerField()),
                ('presc_texto_livre', models.IntegerField()),
                ('presc_template', models.IntegerField()),
                ('presc_pct_texto_livre', models.FloatField()),
                ('presc_pct_template', models.FloatField()),
                ('par_texto_livre', models.IntegerField()),
                ('par_template', models.IntegerField()),
                ('par_pct_texto_livre', models.FloatField()),
                ('par_pct_template', models.FloatField()),
            ],
            options={
                'verbose_name': 'Execução de Análise',
                'verbose_name_plural': 'Execuções de Análise',
                'ordering': ['-criado_em'],
            },
        ),
    ]
