# Generated by Django 6.0.5 on 2026-05-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analise_exploratoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='execucaoanalise',
            table='tb_mestre_execucao_analise',
        ),
    ]
