# Generated by Django 6.0.5 on 2026-05-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analise_exploratoria', '0002_alter_execucaoanalise_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='execucaoanalise',
            table='tb_anonclin_execucao_analise',
        ),
    ]
