# Generated by Django 6.0.5 on 2026-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_exploratoria', '0003_alter_execucaoanalise_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaoanalise',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
