# Generated by Django 6.0.5 on 2026-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_exploratoria', '0004_execucaoanalise_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaoanalise',
            name='especialidades_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
