# Generated by Django 6.0.5 on 2026-05-21 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_exploratoria', '0005_execucaoanalise_especialidades_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Experimento',
                'verbose_name_plural': 'Experimentos',
                'db_table': 'tb_anonclin_experimento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='execucaoanalise',
            name='experimento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='analise_exploratoria.experimento'),
        ),
    ]
