# Generated by Django 6.0.5 on 2026-05-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analise_exploratoria', '0006_experimento_execucaoanalise_experimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoPreprocessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('amostra_por_tipo', models.IntegerField(blank=True, null=True)),
                ('total_documentos', models.IntegerField()),
                ('total_sentencas', models.IntegerField()),
                ('total_prescricoes', models.IntegerField()),
                ('total_pareceres', models.IntegerField()),
                ('presc_texto_livre', models.IntegerField(blank=True, null=True)),
                ('presc_template', models.IntegerField(blank=True, null=True)),
                ('presc_pct_texto_livre', models.FloatField(blank=True, null=True)),
                ('presc_pct_template', models.FloatField(blank=True, null=True)),
                ('par_texto_livre', models.IntegerField(blank=True, null=True)),
                ('par_template', models.IntegerField(blank=True, null=True)),
                ('par_pct_texto_livre', models.FloatField(blank=True, null=True)),
                ('par_pct_template', models.FloatField(blank=True, null=True)),
                ('caminho_conll', models.CharField(blank=True, max_length=500, null=True)),
                ('caminho_jsonl', models.CharField(blank=True, max_length=500, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('experimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preprocessamento', to='analise_exploratoria.experimento')),
            ],
            options={
                'verbose_name': 'Execução de Pré-processamento',
                'verbose_name_plural': 'Execuções de Pré-processamento',
                'db_table': 'tb_anonclin_execucao_preprocessamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
