# Generated by Django 6.0.5 on 2026-06-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaopreprocessamento',
            name='caminho_anotacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='execucaopreprocessamento',
            name='selecao_phi',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
