# Generated by Django 5.2.16 on 2026-08-03 20:52
# Ajustado manualmente: mantém apenas a criação de ExecucaoExtracaoMV, sem o AlterField
# incidental em execucaopreprocessamento.id (drift pré-existente, não relacionado a esta mudança).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_exploratoria', '0006_experimento_execucaoanalise_experimento'),
        ('preprocessamento', '0002_execucaopreprocessamento_caminho_anotacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoExtracaoMV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_execucao', 'Em execução'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='em_execucao', max_length=20)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('hospitais_incluidos', models.CharField(blank=True, max_length=50)),
                ('teto_prescricoes', models.IntegerField(blank=True, null=True)),
                ('batch_size', models.IntegerField(blank=True, null=True)),
                ('caminho_sqlite', models.CharField(blank=True, max_length=500, null=True)),
                ('caminho_log', models.CharField(blank=True, max_length=500, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('experimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracoes_mv', to='analise_exploratoria.experimento')),
            ],
            options={
                'verbose_name': 'Execução de Extração MV',
                'verbose_name_plural': 'Execuções de Extração MV',
                'db_table': 'tb_anonclin_execucao_extracao_mv',
                'ordering': ['-criado_em'],
            },
        ),
    ]
