# Generated by Django 6.0.5 on 2026-08-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessamento', '0003_alter_execucaopreprocessamento_id_execucaoextracaomv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaoextracaomv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
