# Generated by Django 6.0.5 on 2026-05-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analise_exploratoria', '0006_experimento_execucaoanalise_experimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoAnotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_sentencas_amostra', models.IntegerField()),
                ('kappa', models.FloatField(blank=True, null=True)),
                ('kappa_meta_atingida', models.BooleanField(blank=True, null=True)),
                ('concordancia_obs', models.FloatField(blank=True, null=True)),
                ('concordancia_esp', models.FloatField(blank=True, null=True)),
                ('total_tokens_kappa', models.IntegerField(blank=True, null=True)),
                ('total_sentencas_anotadas', models.IntegerField(blank=True, null=True)),
                ('distribuicao_entidades_json', models.JSONField(blank=True, null=True)),
                ('caminho_conll_anotado', models.CharField(blank=True, max_length=500, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('experimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotacao', to='analise_exploratoria.experimento')),
            ],
            options={
                'verbose_name': 'Execução de Anotação',
                'verbose_name_plural': 'Execuções de Anotação',
                'db_table': 'tb_anonclin_execucao_anotacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoDivisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_treino', models.IntegerField()),
                ('total_dev', models.IntegerField()),
                ('total_teste', models.IntegerField()),
                ('verificacao_ok', models.BooleanField()),
                ('ausentes_dev_json', models.JSONField(blank=True, null=True)),
                ('ausentes_teste_json', models.JSONField(blank=True, null=True)),
                ('distribuicao_json', models.JSONField(blank=True, null=True)),
                ('caminho_train', models.CharField(blank=True, max_length=500, null=True)),
                ('caminho_dev', models.CharField(blank=True, max_length=500, null=True)),
                ('caminho_teste', models.CharField(blank=True, max_length=500, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('experimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisao', to='analise_exploratoria.experimento')),
            ],
            options={
                'verbose_name': 'Execução de Divisão',
                'verbose_name_plural': 'Execuções de Divisão',
                'db_table': 'tb_anonclin_execucao_divisao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nome_modelo', models.CharField(choices=[('CRF', 'CRF Baseline'), ('BioBERTpt-clin', 'BioBERTpt-clin'), ('BERTimbau-leNER', 'BERTimbau-leNER'), ('mmBERT', 'mmBERT'), ('ModernBERT', 'ModernBERT')], max_length=50)),
                ('hiperparametros_json', models.JSONField(blank=True, null=True)),
                ('epochs', models.IntegerField(blank=True, null=True)),
                ('tempo_treinamento_seg', models.FloatField(blank=True, null=True)),
                ('classes_json', models.JSONField(blank=True, null=True)),
                ('caminho_modelo', models.CharField(blank=True, max_length=500, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('experimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='analise_exploratoria.experimento')),
            ],
            options={
                'verbose_name': 'Execução de Treinamento',
                'verbose_name_plural': 'Execuções de Treinamento',
                'db_table': 'tb_anonclin_execucao_treinamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('f1_entity_micro', models.FloatField(blank=True, null=True)),
                ('f1_por_entidade_json', models.JSONField(blank=True, null=True)),
                ('f1_token_macro', models.FloatField(blank=True, null=True)),
                ('f1_token_weighted', models.FloatField(blank=True, null=True)),
                ('relatorio_json', models.JSONField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('treinamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='ner.execucaotreinamento')),
            ],
            options={
                'verbose_name': 'Execução de Avaliação',
                'verbose_name_plural': 'Execuções de Avaliação',
                'db_table': 'tb_anonclin_execucao_avaliacao',
                'ordering': ['-criado_em'],
            },
        ),
    ]
